### ISSUE TITLE
installation  - step 15 error

### ISSUE THREAD

**Issue by iubunter** [martinbenson/deep-photo-styletransfer#13]
Hello!

Could you help with installation?
I got the error:

```
Step 15/15 : RUN make clean && make && pip3 install -r gen_laplacian/requirements.txt
 ---> Running in fbb4b33d7fa1
find . -type f | xargs -n 5 touch
rm -f libcuda_utils.so  
/usr/local/cuda-8.0/bin/nvcc -arch sm_35 -O3 -DNDEBUG --compiler-options '-fPIC' -o libcuda_utils.so --shared cuda_utils.cu -I/root/torch/install//include/THC -I/root/torch/install//include/TH -I/root/torch/install//include -L/root/torch/install//lib -Xlinker -rpath,/root/torch/install//lib -lluaT -lTHC -lTH -lpng
Could not open requirements file: [Errno 2] No such file or directory: 'gen_laplacian/requirements.txt'
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/bash -c make clean && make && pip3 install -r gen_laplacian/requirements.txt' returned a non-zero code: 1
```

And when I try run: 

```
root@9ff4f0a3f97c:~/deep_photo# python3 gen_all.py 
Traceback (most recent call last):
  File "gen_all.py", line 163, in <module>
    if not os.path.exists(args.laplacian_directory):
  File "/usr/lib/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: can't specify None for path argument
root@9ff4f0a3f97c:~/deep_photo# 
```

I'd very appreciate any help!

**Comment by martinbenson** [comment]
Ah, sorry. I've just realised that i broke the dockerfile i made some changes to the repo. I'll fix it, but in the meantime if you edit the dockerfile and replace "pip3 install -r gen_laplacian/requirements.txt" with "pip3 install numpy scipy" it should work.

The error from gen_all.py is because you need to specify a bunch of directories to say where various files are located. See the project readme. If you supply a value for every argument it'll work, though some do have default values (but some - including directories - don't).

**Comment by iubunter** [comment]
Thank you very much, it works! 

BTW, there was another problem, when I run gen_all with params:

`ImportError: Could not import the Python Imaging Library (PIL) required to load image files.  Please refer to http://pillow.readthedocs.org/en/latest/installation.html for installation instructions.`

But the command 'pip3 install Pillow' solve it.

**Comment by martinbenson** [comment]
Oops, yes, that's needed too! Thanks. Fixed now.
