### ISSUE TITLE
Segmentation/masking temporarily removed

### ISSUE THREAD

**Issue by martinbenson** [martinbenson/deep-photo-styletransfer#26]

**Comment by ProGamerGov** [comment]
Have you made anyone progress on re-adding segmentation/masking? Preferably with multi style image support?

**Comment by ProGamerGov** [comment]
For anyone needing to use segmentation masks, you can use: 
`git checkout 262a825` to change the version of your directory back to the old version with the working masks.

**Comment by martinbenson** [comment]
I decided to do it in two parts - adopt Johnson's new code without sorting out the masking part, and then after sort that out. It didn't look too hard, so am hopeful that i can do it next time i have a few hours - unless someone beats me to it!

**Comment by ProGamerGov** [comment]
@martinbenson Going beyond the scope Deep Photo Style Transfer research paper, another somewhat recently released research paper addresses some issue with segmentation in regards to style transfer. Because these two papers seem to have been published within a short period of time of each other, the work done in either could not have been used in the other's code. 

I don't know how much of an issue the receptive field problem in regards to Spatial Control (style transfer with segmentation) is with deep-photo-styletransfer, but Leon Gatys' [NeuralImageSynthesis](https://github.com/leongatys/NeuralImageSynthesis) solves the issue via adding in place dilation to the style loss function. Specifically, the relevant code is in the [LossLayers.lua](https://github.com/leongatys/NeuralImageSynthesis/blob/master/LossLayers.lua) file. In the research paper, I believe that the in-place dilation is called "eroded guidance channels", where "guidance channels" refers to inputs and settings that effect your output.

**Comment by DenisSergeevitch** [comment]
Wow, thats why I cannot use  "-content_seg" option

**Comment by martinbenson** [comment]
I have now re-implemented segmentation/masks!
