### ISSUE TITLE
Where is the laplacian file?

### ISSUE THREAD

**Issue by vermontleo** [martinbenson/deep-photo-styletransfer#28]
Hello, everyone.
I'v installed docker ce and @martinbenson 's image, and I'm trying out this code
`deep_photo# python3 deep_photo.py -laplacian`
And I saw this

> -laplacian LAPLACIAN  laplacian file location

But I cannot find the laplacian file
Am I wrong?
Thanks

**Comment by martinbenson** [comment]
The code will create the laplacian file if needed. If you don't specify a value for that parameter it will just create laplacian.csv in the same directory as deep_photo.py. But, calculating the laplacian matrix is time consuming and you don't really want to calculate it if you don't have to. So you can specify a location and if it finds the file then it just loads it rather than recalculating.

Note that the laplacian matrix is specific to the image sized used and you cannot recycle it if you change image size (without getting weird results). So, i tend to name the files <image name>_<image_size>.csv

**Comment by vermontleo** [comment]
Thanks a lot.
I got it.
You are so nice.

**Comment by ProGamerGov** [comment]
@vermontleo I made a standalone version of the laplacian creator here, if you don't want to use `deep_photo.py`: https://gist.github.com/ProGamerGov/290f26afccc5e013d1a8425ef6a594f2
